organization_names:
  - Apple
  - Microsoft
  - Amazon
  - Google
  - Facebook
  - Alibaba
  - Tencent
  - Berkshire Hathaway
  - Visa
  - Johnson & Johnson
  - Samsung
  - Walmart
  - Nestle
  - Procter & Gamble
  - Roche
  - NVIDIA
  - TSMC
  - LVMH
  - Mastercard
  - Intel
  - Verizon
  - Coca-Cola
  - Pfizer
  - Toyota
  - AT&T
  - Netflix
  - PepsiCo
  - Cisco
  - Nike
  - Oracle
  - IBM
  - Unilever
  - Adobe
  - Salesforce
  - PayPal
  - AbbVie
  - ExxonMobil
  - Chevron
  - Novartis
  - Walt Disney
  - Merck
  - McDonald's
  - L'Oréal
  - Costco
  - Boeing
  - Siemens
  - Honeywell
  - Qualcomm
  - SAP

western_nicknames:
  - Buck
  - Tex
  - Dusty
  - Slim
  - Red
  - Duke
  - Maverick
  - Colt
  - Rusty
  - Blaze
  - Ace
  - Hank
  - Wyatt
  - Boone
  - Ringo
  - Jed
  - Cash
  - Chet
  - Jeb
  - Wade
  - Doc
  - Zeke
  - Cody
  - Levi
  - Laramie
  - Reno
  - Stetson
  - Chance
  - Ryder
  - Flint
  - Grady
  - Tuck
  - Ranger
  - Denver
  - Clint
  - Tex
  - Sawyer
  - Beau
  - Dallas
  - Jesse
  - Montana
  - Tripp
  - Nash
  - Walker
  - Kit
  - Brant
  - Ford
  - Gage
  - Jace
  - Rebel


wiki_categories:
  - Almanacs
  - Atlases
  - Biographical dictionaries
  - Dictionaries
  - Encyclopedias
  - Glossaries
  - Handbooks and manuals
  - Lists
  - Medical manuals
  - Reference book stubs
  - Reference works in the public domain
  - Style guides
  - Trivia books
  - Web sites
  - Classics
  - Critical theory
  - Cultural anthropology
  - Clothing
  - Folklore
  - Food and drink culture
  - Food and drink
  - Language
  - Literature
  - Museology
  - Mythology
  - Philosophy
  - Popular culture
  - Science and culture
  - Traditions
  - Handicrafts
  - Celebrity
  - Censorship in the arts
  - Festivals
  - Humor
  - Literature
  - Museums
  - Parties
  - Poetry
  - Circuses
  - Dance
  - Film
  - Music
  - Opera
  - Storytelling
  - Theatre
  - Board games
  - Card games
  - Dolls
  - Puppetry
  - Puzzles
  - Role-playing games
  - Video games
  - Earth
  - World
  - Bodies of water
  - Cities
  - Communities
  - Continents
  - Countries
  - Deserts
  - Lakes
  - Landforms
  - Mountains
  - Navigation
  - Oceans
  - Populated places
  - Protected areas
  - Regions
  - Rivers
  - Subterranea
  - Territories
  - Towns
  - Villages
  - Health by country
  - Health care
  - Health law
  - Health promotion
  - Health standards
  - Hospitals
  - Occupational safety and health
  - Pharmaceutical industry
  - Pharmaceuticals policy
  - Safety
  - Africa
  - Asia
  - Europe
  - America
  - Activism
  - Agriculture
  - Arts
  - Aviation
  - Commemoration
  - Communication
  - Crime
  - Design
  - Education
  - Entertainment
  - Fictional activities
  - Fishing
  - Food and drink preparation
  - Government
  - Hunting
  - Industry
  - Leisure activities
  - Navigation
  - Observation
  - Performing arts
  - Physical exercise
  - Planning
  - Politics
  - Recreation
  - Religion
  - Human spaceflight
  - Sports
  - Trade
  - Transport
  - Travel
  - Underwater human activities
  - Underwater diving
  - War
  - Work
  - Clothing
  - Employment
  - Entertainment
  - Food and drink
  - Games
  - Health
  - Hobbies
  - Home
  - Income
  - Interpersonal relationships
  - Leisure
  - Love
  - Motivation
  - Personal development
  - Pets
